[package]
name = "blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = {version="0.15.6",features=["rayon","blas"]}
rayon = "1.7.0"
cblas = "0.4.0"
transpose = "0.2.2"